# Dependencies
# Using kramdown rather than redcarpet because of Latex support
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Chris Said
description:      'I am a data scientist at Propel. This blog is mostly about statistics, technology, and science.'
url:              https://chris-said.io
baseurl:          /

author:
  name:           'Chris Said'
  url:            http://www.twitter.com/Chris_Said

paginate:         5

github:
  repo:           https://github.com/csaid/csaid.github.io

pages_list:
  Home: '/'
  Feed: '/atom.xml'

# So I can date posts in the future and still have them appear now.
future: true

kramdown: 
  parse_block_html: true

repository: csaid/csaid.github.io