# Dependencies
# Using kramdown rather than redcarpet because of Latex support
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            The File Drawer
tagline:          'A blog by Chris Said'
description:      'My name is Chris Said and I am a data scientist at Opendoor. This blog is mostly about tech, stats, and science.'
url:              http://www.chris-said.io
baseurl:          /

author:
  name:           'Chris Said'
  url:            http://www.twitter.com/Chris_Said

paginate:         5

# Custom vars
version:          2.1.0

gems: [jekyll-paginate]

github:
  repo:           https://github.com/csaid/csaid.github.io


pages_list:
  Home: '/'
  Archive: '/archive'
  Feed: '/atom.xml'

# So I can date posts in the future and still have them appear now.
future: true

